### ISSUE TITLE
Notebook re-review

### ISSUE THREAD

**Issue by adelnehme** [datacamp/string-manipulation-in-sql-live-training#2]
#### General 

- [x] 🔧 **A.** Consider adding another Q&A session between Task 3 and 4

- [x] 🔧 **B.** Change title of the session (currently: "PostgreSQL Live Training Template")

- [x] 🔧 **C.** Remove the "Recap and Closing" section

#### Task 4: Using `CASE` statements to create new categorical fields

- [x] 🔧 **1.** Probably worth adding a reminder on `CASE WHEN` statements in markdown similar to how we did in nested selects. 

#### Extracting string data using split_part()

- [x] 🔧 **2.** Consider using this format for the split part image since it allows you to control alignment and size. 

```html
<p align="center">
<img src="link" alt = "alt-text" width="100%">
</p>
<br><br>
```

### What to keep in the student notebook

- [x] 🔧 **3.** Empty out all code cells of everything except for `%% sql` and the code comment of the cell.

- [x] 🔧 **4.** List of markdown to **keep**:

> - Problems and todo list in **Getting out Data analysis ready**
> - Description underneath **Task 1: Converting data ..**
> - Description underneath **Task 2: Converting data ..** should be changed to just brief discussion about `unnest` and `string_to_array` and mentioning the simple subquery structure.
> - Description underneath **Task 3: Removing leading and trailing whitespace ..** 
> - Description underneath **Task 5: Removing leading and trailing whitespace ..**  and `split_part()`
> - All the markdown after **step 5** should be **kept**

### Intangibles

- [x] **1.** Awesome work adding trimming white spaces in "**Task 2: Using `ARRAYS` to manipulate strings stored as comma-separated-values**" - make sure to mention that the homeway value is 38 after trimming rather than 37 to drive the point home.
